on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  sync-chart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git clone https://${{ github.token }}@github.com/CottonAcademy/Crazy-Kubernetes.git
        rm -rf Crazy-Kubernetes/test
        cp -r test Crazy-Kubernetes/
        cd Crazy-Kubernetes/
        git add .
        git commit -m "update ks-core helm chart"
        git push origin master:update-ks-core
        # gh pr create --title "The bug is fixed" --body "Everything works again"
      env:
        GH_TOKEN: ${{ github.token }}