---
name: Kubernetes-Auto-Support

on:
  schedule:
    - cron: '35 * * * *'

jobs:
  update-kubernetes-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependiencies
        run: |
          wget https://attack-on-titan.gd2.qingstor.com/qsctl/v2.4.3/qsctl_v2.4.3_linux_amd64.tar.gz
          tar -zcvf qsctl_v2.4.3_linux_amd64.tar.gz
          mv qsctl_v2.4.3_linux_amd64 /usr/local/bin/qsctl
          qsctl 
          

